version: '3.4'

services:
  app:
    container_name: api-express-typeorm
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - mariadb
      - redisdb

  mariadb:
    container_name: mariadb-api-express-typeorm
    image: mariadb
    expose:
      - "3306"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_volume:/var/lib/mysql

  redisdb:
    container_name: redisdb-api-express-typeorm
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_volume:
  redis_data:
